{% set name = "wmctrl" %}
{% set version = "0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wmctrl-{{ version }}.tar.gz
  sha256: 7839a36b6fe9e2d6fd22304e5dc372dbced2116ba41283ea938b2da57f53e962

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - attrs
    - __unix  # [unix]
    - __win  # [win]
    - wmctrl-cli  # [unix]

test:
  imports:
    - wmctrl
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/antocuni/wmctrl
  summary: A tool to programmatically control windows inside X
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kynan
    - sodre
    - ehfd
